// <auto-generated />
using System;
using Lab_02.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab_02.Migrations
{
    [DbContext(typeof(Lab01Context))]
    [Migration("20260116140457_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab_02.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Authors__3214EC274A3321D9");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Lab_02.Models.AuthorInfoView", b =>
                {
                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Full Name");

                    b.Property<int?>("NumberOfTitles")
                        .HasColumnType("int")
                        .HasColumnName("Number Of Titles");

                    b.Property<double>("ValueOfStock")
                        .HasColumnType("float")
                        .HasColumnName("Value of Stock");

                    b.ToTable((string)null);

                    b.ToView("AuthorInfoView", (string)null);
                });

            modelBuilder.Entity("Lab_02.Models.Book", b =>
                {
                    b.Property<long>("Isbn")
                        .HasColumnType("bigint")
                        .HasColumnName("ISBN");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("English");

                    b.Property<double?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("PublisherID");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Isbn")
                        .HasName("PK__Books__447D36EB9A512187");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Isbn = 9780241714348L,
                            Language = "English",
                            Price = 215.0,
                            PublisherId = 6,
                            ReleaseDate = new DateOnly(2025, 9, 23),
                            Title = "Alchemised"
                        },
                        new
                        {
                            Isbn = 9780349437057L,
                            Language = "English",
                            Price = 142.0,
                            PublisherId = 4,
                            ReleaseDate = new DateOnly(2024, 11, 19),
                            Title = "Iron Flame"
                        },
                        new
                        {
                            Isbn = 9780349437071L,
                            Language = "English",
                            Price = 210.0,
                            PublisherId = 4,
                            ReleaseDate = new DateOnly(2025, 1, 21),
                            Title = "Onyx Storm"
                        },
                        new
                        {
                            Isbn = 9781035414505L,
                            Language = "English",
                            Price = 147.0,
                            PublisherId = 5,
                            ReleaseDate = new DateOnly(2024, 1, 18),
                            Title = "The Book of Azrael"
                        });
                });

            modelBuilder.Entity("Lab_02.Models.BookAuthor", b =>
                {
                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<long?>("Isbn")
                        .HasColumnType("bigint")
                        .HasColumnName("ISBN");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Isbn");

                    b.ToTable("BookAuthor", (string)null);
                });

            modelBuilder.Entity("Lab_02.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Costumer__3214EC270DA0E6BC");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("Lab_02.Models.CostumerPurchasesView", b =>
                {
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Full Name");

                    b.Property<int?>("NumberOfPurchesedArticles")
                        .HasColumnType("int")
                        .HasColumnName("Number of Purchesed articles");

                    b.Property<string>("PurchasedTitles")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Purchased Titles");

                    b.Property<double?>("TotalSpent")
                        .HasColumnType("float")
                        .HasColumnName("Total spent");

                    b.ToTable((string)null);

                    b.ToView("CostumerPurchasesView", (string)null);
                });

            modelBuilder.Entity("Lab_02.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int?>("WorkPlaceId")
                        .HasColumnType("int")
                        .HasColumnName("WorkPlaceID");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC27D51EC65A");

                    b.HasIndex("WorkPlaceId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Lab_02.Models.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.Property<int>("CostumerId")
                        .HasColumnType("int")
                        .HasColumnName("CostumerID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("StoreCode")
                        .HasColumnType("int");

                    b.HasKey("OrderNumber")
                        .HasName("PK__Orders__CAC5E742D485D3A0");

                    b.HasIndex("CostumerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StoreCode");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lab_02.Models.OrderItem", b =>
                {
                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("ItemIsbn")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemISBN");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.HasIndex("ItemIsbn");

                    b.HasIndex("OrderNumber");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Lab_02.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Publishe__3214EC27E8DB943B");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allen Unwin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiptree Book Service"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grantham Book Service"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Little Brown Book Group"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Headline Publishing Group"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Penguin Books Ltd."
                        });
                });

            modelBuilder.Entity("Lab_02.Models.StockStatus", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("StoreID");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookID");

                    b.Property<int?>("InStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("StoreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("StockStatus", (string)null);
                });

            modelBuilder.Entity("Lab_02.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Stores__3214EC270BBFD00D");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Krokegårdsgatan 5, Göteborg",
                            Name = "Göteborg Backaplan"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Prästvägen 1, Halmstad",
                            Name = "Halmstad Hallarna"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Hantverkaregatan 1, Karlskrona",
                            Name = "Karlskrona"
                        });
                });

            modelBuilder.Entity("Lab_02.Models.Book", b =>
                {
                    b.HasOne("Lab_02.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .IsRequired()
                        .HasConstraintName("FK_PublisherID");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Lab_02.Models.BookAuthor", b =>
                {
                    b.HasOne("Lab_02.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK_AuthorID");

                    b.HasOne("Lab_02.Models.Book", "IsbnNavigation")
                        .WithMany()
                        .HasForeignKey("Isbn")
                        .HasConstraintName("FK_ISBN");

                    b.Navigation("Author");

                    b.Navigation("IsbnNavigation");
                });

            modelBuilder.Entity("Lab_02.Models.Employee", b =>
                {
                    b.HasOne("Lab_02.Models.Store", "WorkPlace")
                        .WithMany("Employees")
                        .HasForeignKey("WorkPlaceId")
                        .HasConstraintName("FK_WorkPlaceID");

                    b.Navigation("WorkPlace");
                });

            modelBuilder.Entity("Lab_02.Models.Order", b =>
                {
                    b.HasOne("Lab_02.Models.Costumer", "Costumer")
                        .WithMany("Orders")
                        .HasForeignKey("CostumerId")
                        .IsRequired()
                        .HasConstraintName("FK_CostumerID");

                    b.HasOne("Lab_02.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_EmployeeID");

                    b.HasOne("Lab_02.Models.Store", "StoreCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("StoreCode")
                        .IsRequired()
                        .HasConstraintName("FK_StoreCode");

                    b.Navigation("Costumer");

                    b.Navigation("Employee");

                    b.Navigation("StoreCodeNavigation");
                });

            modelBuilder.Entity("Lab_02.Models.OrderItem", b =>
                {
                    b.HasOne("Lab_02.Models.Book", "ItemIsbnNavigation")
                        .WithMany()
                        .HasForeignKey("ItemIsbn")
                        .IsRequired()
                        .HasConstraintName("FK_ItemISBN");

                    b.HasOne("Lab_02.Models.Order", "OrderNumberNavigation")
                        .WithMany()
                        .HasForeignKey("OrderNumber")
                        .IsRequired()
                        .HasConstraintName("FK_OrderNumber");

                    b.Navigation("ItemIsbnNavigation");

                    b.Navigation("OrderNumberNavigation");
                });

            modelBuilder.Entity("Lab_02.Models.StockStatus", b =>
                {
                    b.HasOne("Lab_02.Models.Book", "Book")
                        .WithMany("StockStatuses")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_BookID");

                    b.HasOne("Lab_02.Models.Store", "Store")
                        .WithMany("StockStatuses")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_StoreID");

                    b.Navigation("Book");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Lab_02.Models.Book", b =>
                {
                    b.Navigation("StockStatuses");
                });

            modelBuilder.Entity("Lab_02.Models.Costumer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lab_02.Models.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lab_02.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Lab_02.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");

                    b.Navigation("StockStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
